### ISSUE TITLE
Uploading issues

### ISSUE THREAD

**Issue by GasperStef** [leoclee/7-segment-clock#10]
Hello,

When I try to upload the Clock.ino I get message:

In file included from C:\Users\Uporabnik\Documents\Arduino\libraries\FastLED-master\src/FastLED.h:67,
from C:\Users\Uporabnik\Documents\Arduino\data\sketch_may02c\sketch_may02c.ino:13:
C:\Users\Uporabnik\Documents\Arduino\libraries\FastLED-master\src/fastspi.h:150:23: note: '#pragma message: No hardware SPI pins defined. All SPI access will default to bitbanged output'
150 | # pragma message "No hardware SPI pins defined. All SPI access will default to bitbanged output"
| ^~~~~~~~~~~~~~~~~~~~
C:\Users\Uporabnik\Documents\Arduino\data\sketch_may02c\sketch_may02c.ino: In function 'void _Z13getIPlocationv$part$0()':
sketch_may02c:79:18: error: call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)
79 | if (!http.begin(URL)) {
| ~~^~~~~

And on the end:

exit status 1
call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)

Has anyone same issue and fix it? I will be very gratefull for help.

Thank you.

**Comment by leoclee** [comment]
The installation steps at https://github.com/leoclee/7-segment-clock#installation include tested versions for all software, esp8266, and libraries. Please ensure that you are using the recommended versions that are listed there.

**Comment by leoclee** [comment]
3dc6132a141ba93468e0226780bd4cebc0d2650d fixes this issue, which is caused by using an incompatible version of esp8266 code. The latest code now supports ESP8266 3.1.1
