### ISSUE TITLE
Not found: /

### ISSUE THREAD

**Issue by kd7eir** [leoclee/7-segment-clock#2]
I got all the libraries sorted out, sketch uploaded, wifi credentials and API keys entered. But now when I try to connect all I get in the browser is: Not found: /

**Comment by leoclee** [comment]
Were you able to get it working? I am wondering if you were hitting the correct IP address. One thing to try would be to test it out while connected to the serial monitor of the Arduino IDE, which should print out the IP address it is using.

**Comment by kd7eir** [comment]
I completely erased the flash on the D1 and reloaded and it finally worked.
