### ISSUE TITLE
24-hour format

### ISSUE THREAD

**Issue by Do-while-Bacon** [leoclee/7-segment-clock#3]
Just finished building this. Very cool.

How can I change the format to 24-hour? Also, I believe my API keys are correct, but it has not yet set to the correct timezone. Is there a way I can force this to update, or, will it update if I wait long enough?

Thanks!

**Comment by leoclee** [comment]
The 24 hour format needs to be configured manually for now. In the sketch, find this line, change it to false and upload your sketch again:
```c
bool isTwelveHour = true;
```
I'll leave this issue open until I can make it configurable at runtime from a browser.


Concerning the time zone being incorrect, I would suggest taking a look at the output in the serial monitor to make sure it's not failing on one of the API calls. If everything is looking fine there and it's just a matter of being off by 1 time zone, you may have to manually set the location. Look for this and set it to your zip code:
```c
String location = "";   // set to postal code to bypass geoIP lookup
```
I'll be making this configurable using the browser as well soon. If that still doesn't get the correct time zone, there could be a problem with the Google maps API call.

**Comment by Do-while-Bacon** [comment]
Thanks! All good now.

Oh, and, just a side note: after measuring, cutting, stripping, tinning, and soldering 90 small-ass wires, I never want to take on another electronics project again. :) I severely underestimated how much work this would take, lol.

**Comment by leoclee** [comment]
I'm glad to hear that you got it working. Yeah, it was a lot of work, especially for a soldering beginner like myself, but I really like the result of it--hopefully you enjoy the end result as well!

Would you mind posting a make on the Thingiverse page? I would appreciate that a lot. You're actually the first person that I've heard from who sounds like they've actually finished the project!

**Comment by Do-while-Bacon** [comment]
Make posted!

Yes, I am very happy with the end result. It was a project worth taking on. Thanks for all the time you put in to the instructions. I would have been lost without them.

I am new to soldering as well, so, part of the allure of this was learning to do that. I feel like I've been to boot camp and back. :D
