### ISSUE TITLE
error

### ISSUE THREAD

**Issue by JBHTv** [leoclee/7-segment-clock#8]
C:\Users\JBHTv\Music\7-segment-clock-master\7-segment-clock-master\Arduino\clock\clock.ino: In function 'void _Z13getIPlocationv$part$0()':
clock:79:18: error: call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)
   79 |   if (!http.begin(URL)) {
      |        ~~~~~~~~~~^~~~~
exit status 1
call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)

***************************
this line
if (!http.begin(URL)) {

**Comment by leoclee** [comment]
This seems like an issue with a version incompatibility. Have you tried using the versions specified in the README (https://github.com/leoclee/7-segment-clock/blob/master/README.md)? I found a post on stackoverflow where someone was running into a similar issue using esp8266 3.0.0 (https://stackoverflow.com/q/67702822). Sounds like your options are to either downgrade esp8266 to 2.7.x or update the code to account for the API changes.

**Comment by JBHTv** [comment]
it worked for me
